### ISSUE TITLE
Loading images from jar

### ISSUE THREAD

**Issue by gilbertoverg** [Thizzer/jtouchbar#8]
Hi, I'm trying to find a way to display an image inside a TouchBarButton, I can get the image displayed with this code:
```
TouchBarButton leftButton = new TouchBarButton();
leftButton.setImage(new Image(Test.class.getClassLoader().getResource("img/icon.png").getPath(), true));
leftButton.setImagePosition(1);
```
After generating the jar, the image is not displayed because the returned path is only ```img/icon.png```. To workaround this problem I'm extracting the image from the jar to a temporary directory, is it possible to load the image directly from the jar?

**Comment by ttveldhuis** [comment]
This should definitely be (made) possible. I will look in to this.

**Comment by ttveldhuis** [comment]
I have added a (convenience) method to load the image data in a byte[] (see below). So far, I was unable to find a method to allow the touchbar to load the image from the file path automatically, but since images should not be very large, this solution should work fine. I will leave this issue open and research this some more.

You can now use;

`new Image(Test.class.getClassLoader().getResourceAsStream("img/icon.png"));`

or 

```
byte[] data = ...load image here..;
new Image(data);
```

Please let me know if this works for you.

**Comment by gilbertoverg** [comment]
It works perfectly, thank you for making it possible
